# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20161220_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
